
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 27 13:05:40 EET 2013
//----------------------------------------------------

package automatic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ST = 4;
  public static final int DI = 21;
  public static final int MO = 20;
  public static final int PO = 15;
  public static final int GE = 13;
  public static final int SM = 24;
  public static final int MD = 29;
  public static final int IS = 39;
  public static final int AND = 38;
  public static final int LT = 12;
  public static final int CM = 30;
  public static final int CL = 25;
  public static final int IN = 40;
  public static final int OR = 37;
  public static final int LO = 19;
  public static final int CLASS = 42;
  public static final int IF = 33;
  public static final int LG = 8;
  public static final int ID = 5;
  public static final int LE = 18;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int LB = 22;
  public static final int LA = 9;
  public static final int error = 1;
  public static final int RB = 23;
  public static final int NEWLINE = 26;
  public static final int EQ = 7;
  public static final int ERROR = 31;
  public static final int BL = 3;
  public static final int NO = 11;
  public static final int ELSE = 34;
  public static final int NM = 2;
  public static final int TO = 10;
  public static final int WHILE = 32;
  public static final int DEDENT = 28;
  public static final int NE = 14;
  public static final int DEF = 43;
  public static final int INDENT = 27;
  public static final int GT = 17;
  public static final int AO = 6;
  public static final int ELIF = 35;
  public static final int RAISE = 44;
  public static final int PRINT = 41;
  public static final int DO = 16;
}

